### ISSUE TITLE
Integrate with j2objc-gradle

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#1]
Have you tried using your lib with https://github.com/j2objc-contrib/j2objc-gradle?

I still have problems with the integration.

**Comment by vals-productions** [comment]
I will create and include Android and iOS demo projects in the repository
in the next few days with some readme files. Hope it will help to configure
SQLighter.

**Comment by vals-productions** [comment]
j2objc gradle doesn't seem applicable in this case. Sqlighter does not take part in j2objc conversions. As part of sqlighter you get some classes/interfaces you have to include in your Java project, and you get some classes/protocols that you have to include in your iOS project. As long as you comply with provided java interfaces in your SQLite related Java code, your j2objc converted code is going to work identically in objective c through objective c protocol counterparts. I have checked in 2 demo projects - Android and iOS that are configured according to the above. Demo.java is an example of your business logics code developed in java and converted into Demo\h\m in Objective C through j2objc (in whichever way you do it), but the Demo is not part of sqlighter. It's just an example of how your project should be organized with j2objc on one end and sqlighter on another one. Also, take a look at Bootstrap.java and its Obj-C counterpart.

I also made some updates to docs and made slight code refactoring to make config easier. Hope this helps.

**Comment by confile** [comment]
That is great. I try to get it working with j2objc gradle

**Comment by confile** [comment]
@vals-productions Here is a discussion how to integrate sqlighter into j2objc-gradle

 https://github.com/j2objc-contrib/j2objc-gradle/issues/446#issuecomment-137871196
