### ISSUE TITLE
Improvement: More handy APi

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#12]
The current api is nice but it is still very basic and error prone. 

I was thinking more of something more type save like this in Java: https://github.com/stephencelis/SQLite.swift

What do you think about this?

**Comment by confile** [comment]
@vals-productions Should we close this ore are you interested in a query builder which is adapted to your lib?

**Comment by vals-productions** [comment]
I have some supplemental "handy API" in the prototyping works. I'm not sure exactly how to distribute it yet. sqlighter complexity is - it has parallel implementation in both platforms, and there might be issues keeping both in sync if the project get over complicated.

**Comment by confile** [comment]
What I mean is that you should at least add a Builder for a Query String which work with `SQLighterDb`.  This would just make using this lib more easy and would have nothing to do with the Android or iOS specific part. 

Think about it. If you want I make a pull request which you could improve.

**Comment by confile** [comment]
@vals-productions Could you please comment on this?

**Comment by vals-productions** [comment]
I have something in the works right now. It will, probably, take some more time before I check in the initial version. I plan for it to be a separate library that is compatible with sqlighter. I will, most likely, need help on that one in case people will start using it.

**Comment by confile** [comment]
I would like to help you on that. The design of a query build should be based on a finite state machine pattern. Let me know if I should assist you. I started a small query builder for SQLighter myself. Would be a waste to have two separate projects for the same thing.

**Comment by aminelaadhari** [comment]
Why not use a lib like this one https://github.com/nhaarman/SQLiteBuilder ?

**Comment by confile** [comment]
@aminelaadhari SQLiteBuilder does not work with SQLiter.

**Comment by vals-productions** [comment]
@confile , as I mentioned previously, there is one more library in development that is j2objc compatible and has integration points with sqlighter. Sort of Swiss Army knife that helps with object persistence tasks as well as some others. It showed first signs of life recently, but it is not purified and finalized architecturally yet. If you still have bandwidth and want to help, let me know.

**Comment by aminelaadhari** [comment]
@confile could you give more details why SQLiteBuilder does not work with SQLiter ?
The output of SQLBuilder are sql command strings like "SELECT a,b FROM my_table WHERE a=? AND b=? GROUP BY a ORDER BY a,b LIMIT 5". They can be used directly with SQLite executeSelect methods, no ?

@vals-productions I would like to help too, I sent you a message in linkedin for that purpose.

**Comment by vals-productions** [comment]
@aminelaadhari the builder will most likely work for Android. Cannot tell you regarding iOS though.

**Comment by vals-productions** [comment]
[Amfibian subproject ](https://github.com/vals-productions/sqlighter/blob/master/amfibian.md) introduces elements of object / relational as well as object / JSON mappings.
