### ISSUE TITLE
ResultSetImpl hasNext() should match Java conventions

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#17]
`rs.hasNext()` should return if there are any more data sets. 

Then there should be a method: 

`rs.next()` which sets the cursor to the next position and returns the next dataset.

**Comment by vals-productions** [comment]
This is based on Android implementation where they provide only cursor.moveToNext(); which returns true if the result is available AND moves to the next.

iOS sqlite3 implementation provides implementation identical to the above as well.

I definitely could add "dummy" rs.next() which would do nothing, but that's pointless.

**Comment by confile** [comment]
ok
