### ISSUE TITLE
Cannot compile the code

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#2]
When compiling I get the following error:

```
:sqlighter:ios_arm64DebugSqlighterlibSharedLibrary SKIPPED
:sqlighter:compileIos_arm64DebugSqlighterlibStaticLibrarySqlighterlibObjcpp
/Users/mg/Downloads/Majestella/sqlighter/src/sqlighterlib/objc/SQLighterRsImpl.m:76:54: error: cannot initialize a parameter of type 'const jbyte *' (aka 'const signed char *') with an rvalue of type 'const void *'
    IOSByteArray *ba = [IOSByteArray arrayWithBytes: [ d bytes] count:(int)[d length]];
                                                     ^~~~~~~~~~
/Applications/J2Objc/j2objc-0.9.8b/include/IOSPrimitiveArray.h:152:1: note: passing argument to parameter 'buf' here
PRIMITIVE_ARRAY_INTERFACE(byte, Byte, jbyte)
^
/Applications/J2Objc/j2objc-0.9.8b/include/IOSPrimitiveArray.h:61:54: note: expanded from macro 'PRIMITIVE_ARRAY_INTERFACE'
+ (instancetype)arrayWith##U_NAME##s:(const C_TYPE *)buf count:(NSUInteger)count; \
                                                     ^
1 error generated.

:sqlighter:compileIos_arm64DebugSqlighterlibStaticLibrarySqlighterlibObjcpp FAILED

FAILURE: Build failed with an exception.
```

**Comment by confile** [comment]
@vals-productions I really would like to work with your lib but this error hinders me.

**Comment by vals-productions** [comment]
Since you get this error and I do not, it might be due to different compiler settings. Try to add explicit cast (see below)  and let me know if that fixes the error on your end, I can incorporate this explicit cast to sqlighter as well. Unfortunately I cannot reproduce it on my end myself.

IOSByteArray *ba =
        [IOSByteArray arrayWithBytes: (const char *)[ d bytes] count:(int)[d length]];

But your error actually mentions (const signed char*). Do you have default char signed compiler option somewhere? I think "signed" is causing the actual issue. And since the code is not having/using signed types in this scope, that might be some compiler switch.

**Comment by confile** [comment]
I tried this but now  get this error: 

```
SQLighterRsImpl.m:77:54: error: cannot initialize a parameter of type 'const jbyte *' (aka 'const signed char *') with an rvalue of type 'const char *'
    IOSByteArray *ba = [IOSByteArray arrayWithBytes: (const char *)[ d bytes] count:(int)[d length]];
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~
/Applications/J2Objc/j2objc-0.9.8b/include/IOSPrimitiveArray.h:152:1: note: passing argument to parameter 'buf' here
PRIMITIVE_ARRAY_INTERFACE(byte, Byte, jbyte)
^
/Applications/J2Objc/j2objc-0.9.8b/include/IOSPrimitiveArray.h:61:54: note: expanded from macro 'PRIMITIVE_ARRAY_INTERFACE'
+ (instancetype)arrayWith##U_NAME##s:(const C_TYPE *)buf count:(NSUInteger)count; \
                                                     ^
1 error generated.
```

Any idea?

**Comment by vals-productions** [comment]
Ok, let's go step by step... Can you compile ios-demo-prj without any changes? I'm using the latest xcode 6.4, and the Base SDK is iOS 8.4... Compiler is Apple LLVM 6.1

**Comment by confile** [comment]
No.

![bootstrap_m](https://cloud.githubusercontent.com/assets/64265/9839577/d21ade92-5a7e-11e5-8893-cb23c076a7a9.png)

How do I have to configure j2objc? Where do I have to change the path for it?

**Comment by vals-productions** [comment]
It is covered here: https://github.com/vals-productions/sqlighter/tree/master/demo#ios  , so, rather than changing the path in multiple places, create a link to your j2objc installation directory, it's easier

**Comment by confile** [comment]
Still the same error: 
1. I created a link in the demo dir `ln -s /Applications/J2Objc/j2objc-0.9.8.1/j2objc j2objc` 
2. I changed and ran convert.sh

Still 

```
#include "J2ObjC_source.h"
```

could not be found.

**Comment by vals-productions** [comment]
On step 1 you created the link... that should be enough. Why did you do (2) afterwards? Have you overridden the link created at step (1) with something else?

The bottom line.. the project looks for j2objc includes in the following location, relative to the project root: 

<pre>../j2objc/include </pre>

and libraries in

<pre> ../j2objc/lib </pre>

(relative to project's location), so, open the terminal, get into your demo project's location
1. You have to be in this directory: ... sqlighter/demo
   <pre>
   > pwd
   ... sqlighter/demo
   </pre>
2. create a link while in the directory above:
   <pre>
   ... sqlighter/demo> ln -s /Applications/J2Objc/j2objc-0.9.8.1/j2objc j2objc
   </pre>
3. Verify the link actually worked:
   <pre>
   ... sqlighter/demo> ls -l
   ..... README.md
   ..... andr-demo-prj
   ..... crt-j2objc-link.sh
   ..... ios-demo-prj
   ..... j2objc -> ../../m/j2objc-0.9.7 /\* your unique path to be displayed to the left */
   </pre>
   Make sure the link is setup correctly. 
   <pre>
   > cd j2objc
   > ls
   cycle_finder        j2objc          j2objc_protoc_plugin    lib
   include         j2objc_protoc       j2objcc         man
   </pre>

Make sure you do see include and lib dirs here and they do contain includes and libs.

If suggestion above does not work
1) just go into Build Settings\Search Paths and update Header and Library Search path to your locations, then 
2) go to Build Phases\Link Binary With Libraries and replace entries there with entires in your locations.

**Comment by confile** [comment]
It is really hard to configure. You should strongly consider adding it as a gradle lib for: 
https://github.com/j2objc-contrib/j2objc-gradle

This would help a lot of people to use your lib.

**Comment by vals-productions** [comment]
Well, right now it's a matter of being able to include 3 java files in your Android project, and *.m *.h files in your iOS project. Pretty basic skill. I do not see a j2objc gradle as the right tool to use in this scenario.

I plan on creating creating a JAR file for the android and a lib for iOS and adding those to the repository. That's as simple as it can get.

**Comment by confile** [comment]
> I plan on creating creating a JAR file for the android and a lib for iOS and adding those to the repository. That's as simple as it can get.

That is a good idea you should do that.

**Comment by confile** [comment]
Okay, `./convert.sh` works: 

```
translating ../../../andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Demo.java
Translated 1 file: 0 errors, 0 warnings
translating ../../../andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Bootstrap.java
Translated 1 file: 0 errors, 0 warnings
```

Still I getting errors in the demo project: 

![j2objc_common_h](https://cloud.githubusercontent.com/assets/64265/9962386/c976a2ee-5e25-11e5-810d-3829a7000d27.png)

**Comment by vals-productions** [comment]
This has to do something with how github stores iOS project settings (file encodings or so). There are issues reported at stackoverflow with no solution like this and others: 

http://stackoverflow.com/questions/22106307/cyclic-dependency-in-module-corefoundation-corefoundation-spritekit-cor

The way to bypass it - make a clean clone of the project, and build xcode project as is, with no any changes, like changing the target or anything else. Since this is just a demo project this should be sufficient. 

Myself I have this issue if I use github, but never if I use my own non github git repositories.

My wild guess is - xcode does not recognize/handle properly its own project settings file and, instead of modifying existing preferences, it adds new ones, like instead of changing the target from iphone 6 to iphone 5s it adds both to the project file and this causes lockup and cyclic dependency issues.
