### ISSUE TITLE
copyDbOnce() used for dev and prod?

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#20]
Should dbImpl.copyDbOnce() be used in dev and production?

**Comment by vals-productions** [comment]
I have just updated method's javadoc . Please let me know if this makes it clear. Feel free to suggest doc updates if it's not clear.

https://github.com/vals-productions/sqlighter/blob/master/android/com/vals/a2ios/sqlighter/intf/SQLighterDb.java

**Comment by confile** [comment]
Do I need an initial database file. So far it worked without one for me? Could you please update this in the comment? Thanks.

**Comment by confile** [comment]
This sentence does not make any sense: 

https://github.com/vals-productions/sqlighter/blob/16a6ac5d73d73bf9a6ca485e92e4fc3fb43aebf8/android/com/vals/a2ios/sqlighter/intf/SQLighterDb.java#L82

**Comment by vals-productions** [comment]
You do need the initial file, and this is covered here https://github.com/vals-productions/sqlighter#database-file

If you do not have the file, the error https://github.com/vals-productions/sqlighter/issues/24 you are getting is valid.

**Comment by confile** [comment]
I use the following configuration on iOS: 

```
let dbImpl: SQLighterDbImpl = SQLighterDbImpl()
    dbImpl.setDbNameWithNSString(MMDatabase.databaseName)

    let isDbFileDeployed: Bool = dbImpl.isDbFileDeployed()
    if !isDbFileDeployed {
      println("DatabaseAdapterImpl - setDatabaseWithSQLighterDb(): database not deployed")
    }
    else {
      println("DatabaseAdapterImpl - setDatabaseWithSQLighterDb(): database deployed")
    }

    dbImpl.setOverwriteDbWithBoolean(false) 
dbImpl.openIfClosed()
```

On the first launch I get the following: `database not deployed`. 

Then I did some create table and everything worked. I do not have any external sqplite file which was copied.

**Comment by vals-productions** [comment]
documented here: https://github.com/vals-productions/sqlighter#sqlighterdbcopydbonce
