### ISSUE TITLE
IOS SQLite database could not be initialized

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#24]
When running the following code: 

```
    println("DatabaseAdapterImpl - setDatabaseWithSQLighterDb()")
    let dbImpl: SQLighterDbImpl = SQLighterDbImpl()
    dbImpl.setDbNameWithNSString(MMDatabase.databaseName)

    let isDbFileDeployed: Bool = dbImpl.isDbFileDeployed()
    if !isDbFileDeployed {
      println("DatabaseAdapterImpl - setDatabaseWithSQLighterDb(): database not deployed")
    }
    else {
      println("DatabaseAdapterImpl - setDatabaseWithSQLighterDb(): database deployed")
    }

    dbImpl.setOverwriteDbWithBoolean(false)
    dbImpl.copyDbOnce()
    dbImpl.openIfClosed()
```

I get the following output: 

```
DatabaseAdapterImpl - setDatabaseWithSQLighterDb()
DatabaseAdapterImpl - setDatabaseWithSQLighterDb(): database not deployed
2015-09-21 19:44:21.126 TestApp[62389:994686] 
Source db path: 
/Users/mg/Library/Developer/CoreSimulator/Devices/AE4833C1-296D-41C4-A587-131C9940F3FB/data/Containers/Bundle/Application/44814519-3190-4FC7-A385-3E8F17C21716/TestApp.app/buddyisDB.sqlite3
Dest db path: 
/Users/mg/Library/Developer/CoreSimulator/Devices/AE4833C1-296D-41C4-A587-131C9940F3FB/data/Containers/Data/Application/0630F3FA-A019-4DE5-B4EC-A67F76CFCA87/Documents/buddyisDB.sqlite3
2015-09-21 19:44:21.126 TestApp[62389:994686] Could not copy database
```

It seems that the database could not be created. Could you please fix that?

**Comment by confile** [comment]
Not sure if this is important my database name String is: `buddyisDB.sqlite3`

**Comment by steffimueller** [comment]
+1 I could not get the iOS version running too.

**Comment by vals-productions** [comment]
@steffimueller, what error do you get?

**Comment by vals-productions** [comment]
Here's my log that succeeds. May it be related to file permissions?

Source db path: 
/Users/developer/Library/Developer/CoreSimulator/Devices/8B5AFA1D-5763-401F-8A33-FB420AB936BF/data/Containers/Bundle/Application/1A16C64A-BD23-4191-9FCB-5EC6B3578351/ios-demo-prj.app/sqlite.sqlite
Dest db path: 
/Users/developer/Library/Developer/CoreSimulator/Devices/8B5AFA1D-5763-401F-8A33-FB420AB936BF/data/Containers/Data/Application/B585AA67-10BE-41DD-A1A1-98C33829B70B/Documents/sqlite.sqlite

**Comment by vals-productions** [comment]
Did you, guys made your sqlite database part of the project? It has to be listed in xcode's left panel along with your other project *.h *.m etc files

**Comment by confile** [comment]
The problem was that the file was not there.
