### ISSUE TITLE
What does db.copyDbOnce()?

### ISSUE THREAD

**Issue by steffimueller** [vals-productions/sqlighter#25]
Could you please document this function?

**Comment by vals-productions** [comment]
@steffimueller , I have just updated method's javadoc . Please let me know if this makes it clear. Feel free to suggest doc updates if it's not clear.

https://github.com/vals-productions/sqlighter/blob/master/android/com/vals/a2ios/sqlighter/intf/SQLighterDb.java

**Comment by vals-productions** [comment]
Moved into here https://github.com/vals-productions/sqlighter#sqlighterdbcopydbonce
