### ISSUE TITLE
Store and Retrieve Boolean values

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#26]
Could you please explain how boolean values are stored and retrieved from the SQLighterRs?

**Comment by vals-productions** [comment]
SQlite database as well as many other databases does not support boolean datatype. People use char columns with 'Y' / 'N', or, 'T' / 'F', or, smallest possible numeric columns with 0 and 1's in it.

**Comment by confile** [comment]
thanks @vals-productions
