### ISSUE TITLE
Include transactions

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#28]
Could you please include ``transactions` for the database queries as well.

**Comment by vals-productions** [comment]
They are, actually, supported. I added convenience methods, though.

**Comment by confile** [comment]
@vals-productions is each executeChange() and executeSelect() a transaction?

Is it possible to combine more than one queries in one transaction?

**Comment by vals-productions** [comment]
All queries are autocommitted by default. But if you use beginTransaction/rollback/commmitTransaction, then you can group.

I included an example in the demo

**Comment by confile** [comment]
Just to get you right. When I do not do anything beside two queries the are automatically wrapped in a transaction. Right?

**Comment by vals-productions** [comment]
if you execute two sequential queries without specifying transaction boundaries, they represent two individual transactions. I.e. if the second one fails, the first one does not roll back.

But if you enclose your queries into beginTransaction / commit or rollback transaction, then they either both succeed or both fail/rollback

**Comment by confile** [comment]
thank you
