### ISSUE TITLE
IOS: XCode Warnings

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#29]
SQLighterDbImpl:

```
SQLighterDbImpl.m:26:1: Conflicting return type in implementation of 'isDbFileDeployed': 'jboolean' (aka 'bool') vs 'BOOL' (aka 'signed char')
```

Could you please fix that. Thanks.

**Comment by vals-productions** [comment]
I can change BOOL to jboolean, but they are identical according to J2ObjC headers:

```
typedef BOOL            jboolean;
```

... and I'm not getting these warnings. Are you sure that's not 'signed' from this https://github.com/vals-productions/sqlighter/issues/2 issue again?

**Comment by confile** [comment]
This time I use Xcode7 to compile the code. Yes please change to jboolean I know they are the same but may be Xcode is not so sure :-)

This is the only warning everything else is fine.

**Comment by vals-productions** [comment]
applied.

**Comment by confile** [comment]
thank you
