### ISSUE TITLE
How do you know if a transaction fails?

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#31]
If you do: `public void commitTransaction();` how do you know when a transaction fails and when to rollback? Shouldn't there be an Exception thrown?

**Comment by vals-productions** [comment]
@confile, very good point and actually, this is valid not for transactions only, but for all statements. I'll have to review and make consistent Exception or return type handling across both platforms. 

I'll close this issue and reopen another one with broader scope and refer this issue as a source..
