### ISSUE TITLE
Streamline Exception handling between platforms

### ISSUE THREAD

**Issue by vals-productions** [vals-productions/sqlighter#32]
Triggered by this issue: https://github.com/vals-productions/sqlighter/issues/31

Make sure either Exception handling or return type diagnostics regarding query execution results is consistent across Android/iOS platform.

**Comment by confile** [comment]
This is great. I love to test this.

**Comment by vals-productions** [comment]
Changes checked-in. https://github.com/vals-productions/sqlighter#exception-and-error-handling

**Comment by confile** [comment]
thanks
