### ISSUE TITLE
Example in Android Demo when Transaction fails 

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#33]
Could you please add an example in the Android Demo when you compile two queries ore mor in a transaction and force the transaction to fail. 

I think this would be a good example.

**Comment by vals-productions** [comment]
The example is at lines 134-174:

https://github.com/vals-productions/sqlighter/blob/master/demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Demo.java
