### ISSUE TITLE
No initial Database file needed

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#34]
You wrote in the Readme: 

> In either way, both Android and iOS projects should contain your initial SQLite database file.

This is not true. I tested it. You can pretty well work without an initial database file and create the initial database in code.

**Comment by vals-productions** [comment]
Have you verified it in both - Android and iOS?

**Comment by confile** [comment]
Yes I tested on IOS and on Android, both.

I just removed `db.copyDbOnce();` and deleted the database file. 

Before the first query I created the table with: 

```
create table if not exists user (name TEXT,email TEXT,id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,data BLOB,height REAL)
```

You should mention this in the Readme somewhere.

**Comment by vals-productions** [comment]
I have updated the doc: https://github.com/vals-productions/sqlighter/blob/master/README.md#database-file , feel free to update if something is not clear
