### ISSUE TITLE
Get Error Message when something goes wrong.

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#38]
Is is possible to get an error message when something goes wrong like when you have a wrong SQL statement?

**Comment by vals-productions** [comment]
sqlighter throws an exception in this case. F.e. the exception with the following message is thrown in 
the demo code:

```
Message: near "updte": syntax error (code 1): , while compiling: updte user set email = ? where email = ?
```

Code:

``` java
                /**
                 * intentional SQL syntax error to model an exception during
                 * transaction execution
                 */
                db.executeChange("updte user set email = ? where email = ?");

```

If something does not work on your end, please give an example to be able to reproduce.
