### ISSUE TITLE
Update Database path on Android Sample

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#39]
Change the Database path here: 

https://github.com/vals-productions/sqlighter/blob/master/demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/MainActivity.java#L21

This should be 

```
db.setDbPath(AppController.getInstance().getApplicationContext().getFilesDir().getParentFile().getPath()"/databases/");
```

See: http://stackoverflow.com/questions/15219755/jni-loading-warning-do-not-hardcode-use-context-getfilesdir-getpath-inst

**Comment by vals-productions** [comment]
Updated the example and Readme.md
