### ISSUE TITLE
not able to access my sqlite.db in assets folder (Android)

### ISSUE THREAD

**Issue by jaycewind** [vals-productions/sqlighter#43]
hi,

i can't seems to access my sqlite.db in the assets folder for my android application. It always throw me "DB file is not deployed" whereby it is not able to access to my sqlite.db resided in my assets folder. Any help is greatly appreciated..thanks very much :)

```
   SQLighterDbImpl db = new SQLighterDbImpl();
    String dbPath =
            this.getApplication().getApplicationContext().getFilesDir()
                    .getParentFile().getPath() + "/databases/";
    db.setDbPath(dbPath);
    db.setDbName("sqlite.sqlite");
    boolean isDbFileDeployed = db.isDbFileDeployed();
    if(!isDbFileDeployed) {
        System.out.println("DB file is not deployed");
    } else {
        System.out.println("DB file is deployed");
    }
```

**Comment by jaycewind** [comment]
i have changed the setDBName to sqlite.db   but still cannot find my database in assets folder. any help?thanks much :)

**Comment by vals-productions** [comment]
You should call "db.copyDbOnce()" before you check db.isDbFileDeployed(). This method actually copies the file from assets into the device.

**Comment by jaycewind** [comment]
i have changed it to sqlite.db but still not working. i tried it  on my mainactivy class, it is working, However in my Application class ( extends Application)  it is not working (DB file is not deployed). But same code i put into the mainactivity class it is working. may i know why?thanks much

**Comment by vals-productions** [comment]
Do you use db.copyDbOnce()?

**Comment by jaycewind** [comment]
yes, here is my code in Application class (extends Application):

```
        db.setDbPath(dbPath);
        db.setDbName("sqlite.db");
        boolean isDbFileDeployed = db.isDbFileDeployed();
        if(!isDbFileDeployed) {
            System.out.println("DB file is not deployed");
           Toast.makeText(getBaseContext(), "DB file is not deployed dbPath="+dbPath,Toast.LENGTH_SHORT).show();

        } else {
            System.out.println("DB file is deployed");
          Toast.makeText(getBaseContext(), "DB file is  deployed dbPath="+dbPath,Toast.LENGTH_SHORT).show();

        }
        db.setContext(this.getApplicationContext());
        db.setOverwriteDb(true);
        try {
            db.copyDbOnce();
            db.openIfClosed();
        } catch (Throwable t) {
            t.printStackTrace();
        }
        Bootstrap.getInstance().setSqLighterDb(db);
```

**Comment by jaycewind** [comment]
String dbPath = this.getApplicationContext().getFilesDir().getParentFile().getPath() + "/databases/";

```
        db.setDbPath(dbPath);
        db.setDbName("sqlite.db");
        boolean isDbFileDeployed = db.isDbFileDeployed();
        if(!isDbFileDeployed) {
            System.out.println("DB file is not deployed");
           Toast.makeText(getBaseContext(), "DB file is not deployed dbPath="+dbPath,Toast.LENGTH_SHORT).show();

        } else {
            System.out.println("DB file is deployed");
          Toast.makeText(getBaseContext(), "DB file is  deployed dbPath="+dbPath,Toast.LENGTH_SHORT).show();

        }
        db.setContext(this.getApplicationContext());
        db.setOverwriteDb(true);
        try {
            db.copyDbOnce();
            db.openIfClosed();
        } catch (Throwable t) {
            t.printStackTrace();
        }
        Bootstrap.getInstance().setSqLighterDb(db);
```

**Comment by vals-productions** [comment]
Database file is not deployed until you call db.copyDbOnce(); (that's in the bottom of your snippet)

So, your check for isDbFileDepoyed() before that (on the top of your snippet) is giving you the correct answer - it is not deployed (yet).

**Comment by jaycewind** [comment]
i see. i got it. And one more question. so i assume that the database is accessible and ready to be inserted and selected. However, i started to find out that i didnt able to access (insert) any to the database neither returned any selected query. could it be due to the database is not accessible?thanks much :)

**Comment by vals-productions** [comment]
It all should work - inserts/updates/selects/ etc.. after you called db.openIfClosed(); Nothing else is needed. If something didn't work, it would either be some business logics error or something else. 
Star the project and enjoy :)

**Comment by jaycewind** [comment]
i see..great..thanks very much. will continue my debugging efforts. thanks for your support man :) best :)

**Comment by jaycewind** [comment]
one more question..is my database reset after i restarted my device?

**Comment by vals-productions** [comment]
db.setOverwriteDb(true); - yes

db.setOverwriteDb(false); - no

**Comment by jaycewind** [comment]
great..now it is working.the whole problem lies on i set it to true. so i kinda not able to get any row after i restarted my device. now it is working. thanks much :) thinking to port my code to  Object C , so that's why i am using your sqlighter. thanks much for your help :)

**Comment by vals-productions** [comment]
yw
