### ISSUE TITLE
Please document how this is meant to be used regarding shared code modules

### ISSUE THREAD

**Issue by Giszmo** [vals-productions/sqlighter#46]
I'm trying to make sense of how to work with sqlighter in our Android/iOS app and miss seeing what goes where.

We have the business logic in a shared module, with the UI in iOS and Android. I assume I would have a share sqlighter interface in the business logic, with the platforms telling it where and how to store the DB but else, the business logic should be able to use the DB, right? Could you please shed some light on how that is meant to look like?

**Comment by vals-productions** [comment]
@Giszmo , please check demo projects that are part of sqlighter. That's Android project with matching iOS project: https://github.com/vals-productions/sqlighter/tree/master/demo

Also, current readme includes Android/iOS configuration documentation: https://github.com/vals-productions/sqlighter#instantiation-example or https://github.com/vals-productions/sqlighter#project-configuration

**Comment by Giszmo** [comment]
Thanks. I'm still confused. I was looking for how to do this in a multi module setup, where shared code lives in a module that primarily uses the DB but with the native code having to actually open the db file.

Buuut .... nevermind. We moved on and I guess it's not worth pushing for this if it's not a widely common requirement. Sorry for bothering ...

**Comment by vals-productions** [comment]
Android native code "uses the DB" on Android platform, and iOS native code "uses the DB" on iOS platform in sqlighter. That's what I can tell. As far as your particular project's setup, not sure I follow it, so can't advice.
