### ISSUE TITLE
startSqlUpdate to support addInclAttribs

### ISSUE THREAD

**Issue by MyCADDev** [vals-productions/sqlighter#50]
Hi,
I want to update multiple rows with same value. Is this possible to implement?
If not is there another way I can do it?

```
AnOrm<SomeData> someOrm = (AnOrm<SomeData>) dbInterface.getOrm(SomeData.class);

SomeData someData = new SomeData();
someData.setDetailsAvailable(1);
someOrm.startSqlUpdate(someData);
someOrm.addWhere("owner_id = ?", ownerId);

// Only use this information
someOrm.addInclAttribs("detailsAvailable");

long returnCode = someOrm.apply().longValue();
```

thanks
Harish

**Comment by vals-productions** [comment]
@MyCADDev - basically, you'd like to use orm to generate and execute "update table set column1 = value1 where <condition>" ? Right?

The demo here: 

https://github.com/vals-productions/sqlighter/blob/master/demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Demo.java

demoes how to execute sql statements like you want using sqlighter directly: 
```
SQLighterDb db = Bootstrap.getInstance().getSqLighterDb();
db.addParamNull(); // set email as null
db.addParam(userEmail);
Long alteredRows = db.executeChange("update user set email = ? where email = ?");
```
Looks like this is shorter way to achieve it.

**Comment by vals-productions** [comment]
Actually, your code should also work, you'd just need to move 
``` someOrm.addInclAttribs("detailsAvailable"); ``` 
above
``` someOrm.startSqlUpdate(someData); ```

So it'd look like: 
```
AnOrm<SomeData> someOrm = (AnOrm<SomeData>) dbInterface.getOrm(SomeData.class);

SomeData someData = new SomeData();
someData.setDetailsAvailable(1);
// Only use this information
someOrm.addInclAttribs("detailsAvailable");
someOrm.startSqlUpdate(someData);
someOrm.addWhere("owner_id = ?", ownerId);

long returnCode = someOrm.apply().longValue();
```
and do not forget to use 

``` someOrm.resetSkipInclAttrNameList(); ```

once you need to get bach to the full list of columns,

**Comment by MyCADDev** [comment]
Thanks for the note.

For now I am using the Sqlighter interface with SQL string syntax and parameters to do the job. 

I'll give your suggestion a try soon.

**Comment by vals-productions** [comment]
Closing. Requested functionality works with suggested code tweak. Also, to make sure, corresponding scenario was added to Amfibian tests.
