### ISSUE TITLE
[db setReplaceDatabase:TRUE] is missing in iOS Demo project

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#7]
In `AppDelegate` you have: 

```
[db setReplaceDatabase:TRUE];
```

This method is not available.

**Comment by confile** [comment]
I think you mean setOverwriteDb

**Comment by vals-productions** [comment]
it is available.

**Comment by confile** [comment]
What is the difference between setOverwriteDb and setReplaceDatabase?

**Comment by vals-productions** [comment]
Oh, I see. There's no difference. setOverwriteDbWithBoolean is required by the protocol, but setReplaceDatabase is synthesized by the declaration of the property. Everything is public in Obj C. I think I just followed compiler hint's prompt and choose the wrong one.
