### ISSUE TITLE
Using OCNI for Native Objective-c Implementation.

### ISSUE THREAD

**Issue by steffimueller** [vals-productions/sqlighter#8]
It would be a great help if you could use OCN: http://j2objc.org/docs/Writing-Native-Methods.html

to write your native objective-c methods in the Java Impl for ios. 

Could you please add these classes? This would make using your lib much better.

**Comment by confile** [comment]
@vals-productions +1 Yes I need this too. I thing this would also help to use it in a gradle project.

**Comment by vals-productions** [comment]
If this approach works for my scenario then I agree, it would make it easier to setup...

I will investigate.

**Comment by MartinBusch** [comment]
+1 on this!

**Comment by vals-productions** [comment]
Ok guys, I've done some quick prototyping, and it sounds like OCNI is the best for... as the title says - "Writing Native Methods" (http://j2objc.org/docs/Writing-Native-Methods.html) . There's no straight way to declare class members... so... there's limitation on implementation of classes and class hierarchies this way at least right now.
